### ISSUE TITLE
Allow for underscore _ non-css-creating partials

### ISSUE THREAD

**Issue by jasonkuhrt** [stylus/stylus#181]
A handy feature from sass is _foo.sass which designates it as a partial. It can be imported into other `.sass` files but will not be compiled into a `.css` file itself.

Sass also makes this nice by allowing you to call the partial without the ugly underscore prefix. It's smart enough to match:

`@import foo_bar_partial` to `_foo_bar_partial.sass`.

Similar abilities in stylus would be great.

**Comment by Stichoza** [comment]
You can just use a pattern to ignore files starting with `_`

```javascript
gulp.task('styles', function() {
  return gulp.src('src/stylus/**/!(_*.styl)')
  // ...
```

/cc https://github.com/LearnBoost/stylus/issues/914

**Comment by hanifbbz** [comment]
:+1: 

It would be really handy if Stylus doesn't "compile" files that start with underscore. This makes the code base very clean because we can mark those "library" files that with underscore and make it clear that they are not to be used separately.

It is kinda like Javascript code. You have one or two executable files and the rest are modules that are used in those main executable files. We have a similar structure in our SASS code: the files that start with _ (partials) are like javascript modules. They are only as good as being "included" in other files. In our case we have one main SASS file that includes those partials and it is only the CSS output of this file that is useful for us. We don't want every single Stylus file in the project source tree to be compiled. Most of them are partials indeed. I vote for a re-open.

**Comment by Panya** [comment]
> It is kinda like Javascript code. You have one or two executable files and the rest are modules that are used in those main executable files. 

Well, as in JS only you and your build script should decide which files will be executable and which will be used as modules :)

**Comment by InkSpeck** [comment]
You can. Point your compile script to your main file/s and use import to import whatever modules you want use.

**Comment by hanifbbz** [comment]
Yeah but these are files that are full of mixins and variables that are shared between other stylus files. In fact compiling such files will generate empty CSS files (probably with some comments) :D

**Comment by Panya** [comment]
> Yeah but these are files that are full of mixins and variables that are shared between other stylus files. In fact compiling such files will generate empty CSS files (probably with some comments) :dancer:

Yeah, but if these files are just mixins and some variables why you would need to compile them separately? It doesn't make sense.

**Comment by InkSpeck** [comment]
If a file contains a mixin needed by another file you simply make sure to import the file containing the mixin first. I find it helpful to create an index file that holds the imports in order then just use that index as your main file or import it into the beginning of your main file.

**Comment by hanifbbz** [comment]
Yeah I understand what you're saying however, partials make it easier by explicitly making it clear that the file is going to be used only as an include and it can't accidentally be converted to a css file.

This is a really handy feature that big libraries like Zurb use: http://zurb.com/university/lessons/35

When I first came across the concept of partials I was thinking "oh, well. yet another stupid concept to learn on top of CSS". But over time it turned out to be my best friend in the SASS word and one of the most important features I missed in LESS. Stylus is super awesome with its concise syntax and independence from Ruby. If it is to replace a strong rival like SASS, it should give us decent replacements for out current toolbox.

It's hard to explain because partials are a handy feature that show their usefulness in huge source codes. See this post for example: http://thesassway.com/beginner/how-to-structure-a-sass-project

**Comment by InkSpeck** [comment]
I guess I'm not seeing the difference here. Essentially that link describes how I'm using stylus. Using stylus' import directive does not compile that file to css it simply imports those css declarations that are in the imported file and makes available any mixins that are in the imported file to the rest of the stylus code that follows. If you want to use one main file and import mixins and smaller "partials" into it...? Simply use the import as described and tell the compiler to only compile that main file this will produce a single css file.

**Comment by hanifbbz** [comment]
There are several use cases that would be more complicated without partials:

1. IDE watchers: for example WebStorm has this neat feature that compiles files on the fly. So the way it works is that whenever you add a sass file to your project, it asks if you want automatic file watchers to watch any changes on the file and compile it to CSS (it has similar features for coffeescript, ECMA 6, LESS, etc.) https://www.jetbrains.com/webstorm/help/file-watchers.html Since SASS ignores compiling partials, it is very easy to just activate the watcher. For LESS however, you have to go the extra mile and define a regular expression for the files to be ignores. LESS misses partials as well.

2. Build scripts: it is much easier to set up a build script that does this: `for every X.styl file generate X.css` For example in gulp:

```
gulp.task('one', function () {
  gulp.src('*.styl')
    .pipe(stylus())
    .pipe(gulp.dest('./css/build'));
});
```

Of course we can *configure* both use cases to ignore partials but if there was a *convention* to replace this *configuration* it would make things much easier. SASS partials are one of the better features that make the language so powerful. LESS is kinda minimalistic and doesn't even have proper iterations. But Stylus is the closest I've found to SASS in the Nodeland. This feature's absence is really itching... :+1:
