### ISSUE TITLE
Hard @extend with `&` reference

### ISSUE THREAD

**Issue by a-x-** [stylus/stylus#1983]
I want use variables in `@extend`

Can i write something like this?:

```stylus
.b-501px-popular-themes
    &__item
        // ... mixin declaration ...
            &_pos_0
                display: block

            for $pos in 1..$thumbs-in-line-count
                &_pos_{$pos}
                    @extends &_pos_{$pos - 1}
```

Error:
`Failed to @extend "&_pos_0"`

**Comment by Panya** [comment]
Currently you cannot use parent reference inside `@extend` (it's just useless, because you're extending inside new block => new value of parent reference), but you can use `selector()` function to dynamically get the selector. But anyway, your current code is trying to extend not `.b-501px-popular-themes__item_pos_0` but `.b-501px-popular-themes__item_pos_{pos}_pos_{$pos - 1}` (because of nesting).

You can define placeholder selectors and use them inside the loop. For example:
```styl
.b-501px-popular-themes
    &__item
            &_pos_0,
            /$pos_0  // use / to eliminate nesting
                display: block

            for $pos in 1..$thumbs-in-line-count
                &_pos_{$pos},
                /$pos_{$pos}
                    @extends $pos_{$pos - 1}
```

**Comment by a-x-** [comment]
Thank you!
I got your more correct way

**Comment by Panya** [comment]
BTW another way to achieve this goal is by saving value of the parent reference to a variable:
```styl
.b-501px-popular-themes
    &__item
            &_pos_0
                display: block

            for $pos in 1..$thumbs-in-line-count
                $parent = selector() // '.b-501px-popular-themes__item'
                &_pos_{$pos}
                  @extends {$parent}_pos_{$pos - 1}
```
