### ISSUE TITLE
Support :matches() expansion

### ISSUE THREAD

**Issue by jcracknell** [stylus/stylus#1986]
Transform:

    .a .b:matches(.c, .d) .e { ... }

to:

    .a .b.c .e, .a .b.d .e { ...}

If the expansion of a selector in the `:matches` selector list contains an incompatible element selector, the selector is dropped with a warning.

**Comment by Panya** [comment]
I'm not sure that we should implement the feature, since it's already in the CSS specification. Also you can easily simulate this feature with code like:
```styl
.a {
}

**Comment by jcracknell** [comment]
Well, the observation is that it will be years before we see the kind of widespread support necessary to use `:matches` directly. This provides a nice shorthand for distributing selector combinators without having to build a staircase.

I had considered parentheses, e.g. `(.c, .d) .e`, but it seemed like the standard syntax should be the way to go.

**Comment by Panya** [comment]
Anyway, when it will be supported in all or at least in two browsers, the feature in Stylus would generate unexpected and confusing code.

The syntax in CSS is awesome, because currently you can't use nesting, but in preprocessors I think it's not a big deal since we always can nest selectors (and even use parent reference) and get desired output. So it would be just a syntax sugar.
