### ISSUE TITLE
Add some es6 functionality around object-literals and arrays

### ISSUE THREAD

**Issue by tjbenton** [stylus/stylus#1988]
It would be really nice to have some of the es6 features around objects and arrays.

## [Enhanced Object Literals](https://github.com/lukehoban/es6features#enhanced-object-literals)

For objects it's extremely nice to be able to set dynamic key names

```
handler = 20
obj = {
 handler, // Shorthand for ‘handler: handler’
 [something()]: 42 // Computed (dynamic) property names
}
``` 

Would also be very nice to be able to set functions in objects so that when people create libs they can put them in a namespace so that they don't conflict with other libs that you might have.
```
namespace = {
 someFunction(){
  ...
  return someValue;
 }
}

.foo{
 margin namespace.someFunction();
}
```
 I realize theres more to it than just adding it since you can already do several other things with objects in stylus, but a guy can hope :wink:. I think this is something that could be a big selling point to other developers who are looking for more functionality than other preprocessors have.

## [Destructuring](https://github.com/lukehoban/es6features#destructuring)

```
// list matching
[a, , b] = [1,2,3];

// object matching
{ op: a, lhs: { op: b }, rhs: c } = getASTNode()

// object matching shorthand
// binds `op`, `lhs` and `rhs` in scope
{op, lhs, rhs} = getASTNode()
```

```
$config = {
 border-radius: 6px,
 border-color: #e2e2e2,
 color: darken(#e2e2e2, 40%),
 font-family: unquote("Lato, Helvetica, Arial, sans-serif"),
 font-size: 14px,
 line-height: 1.4em,
 padding: 10px
};

someFunction(a, b, {color, size: font-size, line-height, ...rest} = config){ 
 ...
}
```

**Comment by Panya** [comment]
While this looks cool and useful in JS and other programming languages, I'm not sure that these features will be widely used in Stylus (maybe except functions inside objects, see #1690). Actually, over 80% of users don't use anything except variables/mixins and nested selectors with parent references. Our parser is already very complex (due to flexibility of the syntax), so I think efforts to implement these features are not worth it.
