### ISSUE TITLE
Cannot check unit

### ISSUE THREAD

**Issue by seleckis** [stylus/stylus#2144]
I need to check unit to be px or something else, but…
```stylus
font-size(args...)
	a = split("/", '' + args)
	p(unit(a[0]))

.selector
	font-size 10px/1.5
```
Got error:
`TypeError: expected "unit" to be a unit, but got string:'10px'`

If I use unquote for a[0], I get error:
`TypeError: expected "unit" to be a unit, but got literal:10px`

How to do it in right way?

**Comment by kizu** [comment]
In that exact case the `arguments[0]` would always be a unit before the `/`, and the `arguments[2]` would be the one after.

You're getting the error because you're first converting the arguments to string, losing the information of what was there.

In cases you'll need this anyway, you could use a [`convert()` bif](http://stylus-lang.com/docs/bifs.html#convertstr).

Also, it is better to use StackOverflow to ask such questions :)

**Comment by seleckis** [comment]
Thank you.
