### ISSUE TITLE
Can we stop parsing stuff by default?

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus#2221]
![image](https://cloud.githubusercontent.com/assets/224636/17670208/e09eb22c-62de-11e6-8dec-977537d91124.png)

I hate that I have to wrap everything in `unquote`.

Can we make the default behavior `unquote` instead of parsing everything? We could add something like `parse()` or `math()` to explicitly tell Stylus to do math operations to things.

Obviously this would be an API-breaking change, but I think it'd be worth it.

Like this kind of conversion "magic" is just objectively bad:

![image](https://cloud.githubusercontent.com/assets/224636/17670346/7c7578d4-62df-11e6-826c-02a69711912f.png)

**Comment by vendethiel** [comment]
Another option would be to just add a "Fraction" type. Less worries about IEE754 as well...

**Comment by vendethiel** [comment]
Well, "just add" is stupid, it'd be some work. But it'd make sense and be nicer for calculations

**Comment by corysimmons** [comment]
tbh I wish Stylus had something like [ES6 template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

This really sucks now that PostCSS is getting popular because Stylus tries to process PostCSS custom syntaxes.

PostCSS' parsers and syntax things are all garbage. It'd be nice if we could simply wrap something in backticks or something and pass raw variables like with ES6 template tags.

```styl
fraction: 1/2

a
  width: calc(100% * `${fraction}`)
  `funkyPostCSSProperty: funkyPostCSSValue`
```

**Comment by MaxArt2501** [comment]
@corysimmons 
> this kind of conversion "magic" is just objectively bad

Nope, this is your personal opinion. And I personally disagree. Stylus would cease to be a preprocessor to become a "process-on-demand" parser.

Both SASS and LESS - the most common preprocessors around - execute expressions as they meet them. The reason is that, statistically, it's what you want most of the times. In fact, both SASS and LESS have "unquote" functions.
I don't see why Stylus should behave differently, having the same purpose. Did you complain about it on those projects too?

I admit that `unquote` is quite verbose to write, so a LESS-like syntax such as `~"..."` would be welcome. But even without it, `unquote` is the lesser evil. I would hate to explicitely tell Stylus to interpolate a variable every time I have to use it. Writing functions and mixins would be a headache.

I don't understand what you tried to show with the second screenshot. Did you make a mistake?

**Comment by corysimmons** [comment]
>I don't see why Stylus should behave differently, having the same purpose. Did you complain about it on those projects too?

Nah I'm banned from Sass and the LESS folks hate me.

> I admit that unquote is quite verbose to write, so a LESS-like syntax such as ~"..." would be welcome.

Sure. I see your point and agree to your proposition of an alias for `unquote`. 👍 

Not sure what I was trying to show with 2nd ss tbh.
