### ISSUE TITLE
css-flipper annotations for RTL stylesheets only apply to first statement of output

### ISSUE THREAD

**Issue by ragesoss** [stylus/stylus#2248]
I have a stylus file that has something like this:

```
  transform translateX(-50%) translateY(-30px) scale(.7, .7)
```

I want to apply an annotation for css-flipper so that it also works for a right-to-left layout, so I do this:

```
  /*@replace: translateX(0) translateY(0) scale(.7, .7)*/ transform translateX(-50%) translateY(-30px) scale(.7, .7)
```

The output is ultimately this:

```
  /*@replace: translateX(0) translateY(0) scale(.7, .7)*/
  -webkit-transform: translateX(0) translateY(0) scale(.7, .7);
  transform: translateX(-50%) translateY(-30px) scale(0.7, 0.7);
```

The `@replace` annotation only carried through for the first line.

**Comment by Panya** [comment]
Not sure that the problem is related to Stylus (see an [example](http://stylus-lang.com/try.html#?code=body%0A%20%20%2F*%40replace%3A%20translateX(0)%20translateY(0)%20scale(.7%2C%20.7)*%2F%0A%20%20transform%20translateX(-50%25)%20translateY(-30px)%20scale(.7%2C%20.7))). Seems like you are using some library for prefixing (autoprefixer? nib?). Try to add prefixes after applying css-flipper.

**Comment by ragesoss** [comment]
Thanks @Panya! It was autoprefixer that did that.

For anyone else who comes searching for a solution to this problem, here's how I solved it: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/24410dca39a3c786f90362ac781dee58d548562a
