### ISSUE TITLE
I have a question I don't know how to solve. add -{$i}  an error

### ISSUE THREAD

**Issue by wanghuaDev** [stylus/stylus#2250]
for $i in  1...{$columns} {
        {$epm-wrapping-class}.col-{$breakpoint}-{$i} {
          make-col($i, $columns, $gutter);
        }
      }

**Comment by Panya** [comment]
Missing the context, but I think the problem is `1...{$columns}`. You should write it without an interpolation: `1...$columns`. See an [example](http://stylus-lang.com/try.html#?code=%24columns%20%3D%205%0A%24epm-wrapping-class%20%3D%20'.some-class'%0A%24breakpoint%20%3D%20'desktop'%0A%24gutter%20%3D%205px%0A%0Amake-col(i%2C%20columns%2C%20gutter)%20%7B%0A%20%20test%3A%20arguments%0A%7D%0A%0Afor%20%24i%20in%20%201...%24columns%20%7B%0A%20%7B%24epm-wrapping-class%7D.col-%7B%24breakpoint%7D-%7B%24i%7D%20%7B%0A%20%20%20make-col(%24i%2C%20%24columns%2C%20%24gutter)%3B%0A%20%7D%0A%7D).
