### ISSUE TITLE
Q: Stylus components, framework?

### ISSUE THREAD

**Issue by cjaoude** [stylus/stylus#2275]
Can't seem to find any good components or frameworks for Stylus. Wassup there? Kind of sucks to have to do things from scratch like responsive navbars, modals, etc. :/

**Comment by vio** [comment]
Using `stylus` since 2014 in medium/large applications, but tbh we had to create most of our stuff from scratch. Not a particularly bad thing since Stylus allowed us to do more and we did things that solved our needs.

For well-known UI libraries, you can find stylus versions (eg: https://www.npmjs.com/package/bootstrap-styl).

Also, here is a list with a bunch of projects that I gathered over time: https://gist.github.com/vio/44201020b30568042e47e81f18a384aa
