### ISSUE TITLE
Override variables

### ISSUE THREAD

**Issue by AndreasCag** [stylus/stylus#2338]
I have flatpickr library, which has some stylus styles.
Inside the library, there are some variables I want to override.
![image](https://user-images.githubusercontent.com/14947036/33234784-789002d8-d23d-11e7-9a8c-92f9b3539e1b.png)

As you can see, аssigning "daySize" value to a variable occurs with `=` instead of `?=`, so I can't act like this: 
![image](https://user-images.githubusercontent.com/14947036/33234768-18fa4234-d23d-11e7-9346-eeb5e16c0a7e.png)
How should I override "daySize" variable? Without flatpickr source code changes.

**Comment by jzucadi** [comment]
Perhaps it is an issue with the order of things getting compiled?

**Comment by Cobelt** [comment]
Hi, I have a problem that looks like this one, but I can't figure out where I'm doing it wrong : 
in my index.js
-> I import a stylus file with primary-color = red 
-> then I import an other stylus file that does primary-color ?= blue and .bg-primary-color
But at the end I have my div with class "bg-primary-color" that appears blue
Thanks for your help, I'm on it since this morning '-'
