### ISSUE TITLE
Expected rgba or hsla, but got call:var(--color-bar) error

### ISSUE THREAD

**Issue by Akiyamka** [stylus/stylus#2380]
```stylus
.foo
    &.bar
        &:hover
            background-color: rgba(var(--color-bar), 0.3)
```
Expected output:
```
.foo.bar:hover {
    background-color: rgba(var(--color-bar), 0.3);
}
```
Got:
```
TypeError: expected rgba or hsla, but got call:var(--color-bar)
```
Stylus version: 0.54.5;
Node version: 8.9.4

**Comment by TylerCompiler** [comment]
Experiencing this exact same issue. I'm suspecting it has something to do with the order in which Stylus parses the document. It appears as though the values for rgba are computed before variable are passed around as this works perfectly fine when assigning the variables value to any other property (assuming the value is of a correct type).

For example:

```
:root
    --val #000

body
    background-color var(--val)
```

will behave exactly as expected. I have found that a temp solution is using the @css rule to around your style like so:

```
@css{
  .foo.bar:hover {
    background-color: rgba(var(--color-bar), 0.3);
  }
}

```

**Comment by xaiki** [comment]
me too ! @TylerCompiler 's fix works here though.

**Comment by darsain** [comment]
What you're trying to do here is impossible. `rgba()` is a stylus function that expands *at **compile** time* into a raw `rgba()` CSS declaration. In your case, you want it to modify the opacity of the color to be `0.3` *at **compile** time*. But `var(--color)` is a CSS function that queries `--color` *at **execution** time*. Stylus cannot expand `var(--color)` at compile time, since that would break CSS at execution time.

You'd than never be able to modify the value with:

```js
// modifying a :root variable
document.documentElement.style.setProperty("--color", "#111");
```

Or rather you would, but it would have no effect.

Also, the raw CSS `rgba()` declaration does not support the `rgba(var(--color), 0.3)` notation (not surprising since it's just a stylus convenience feature), so that `@css` fix just can't work. I guess it compiles, but into an invalid CSS.

As far as I know there is a proposals to include color manipulation functions into CSS spec, but nothing is live right now, so the only way how to do what you are after would be something like this:

```stylus
// stylus variables
foo = #000

// css variables
:root
    --foo foo
    --foo-muted rgba(foo, 0.3)

.foo
    background var(--foo)

    &.muted
        background var(--foo-muted)
```

And if you don't need the ability to modify CSS variables during runtime, than you don't need `var()` at all, and you can just stick to stylus variables.

**Comment by TylerCompiler** [comment]
>What you're trying to do here is impossible. rgba() is a stylus function that expands at compile time into a raw rgba() CSS declaration. In your case, you want it to modify the opacity of the color to be 0.3 at compile time. But var(--color) is a CSS function that queries --color at execution time. Stylus cannot expand var(--color) at compile time, since that would break CSS at execution time.

@darsain   while this certainly holds true for @Akiyamka's example, as hover will not produce any results for them, but referring to your example here:

>You'd than never be able to modify the value with:

>// modifying a :root variable
>document.documentElement.style.setProperty("--color", "#111");

>Or rather you would, but it would have no effect.

> Also, the raw CSS rgba() declaration does not support the rgba(var(--color), 0.3) notation (not surprising since it's just a stylus convenience feature), so that @css fix just can't work. I guess it compiles, but into an invalid CSS.

and combining it with my workaround, I'm not sure why you're saying it won't work, cause it very much does. I went back and tried an example test case I was messing around with a while ago:


### Stylus
```css
:root
	--red 155
	--green 155
	--blue 155

@css{
	body{
		background-color: rgba(var(--red), var(--green), var(--blue), 1)
	}
}
```

### JS
```javascript
const button = document.getElementById('button')

let red = 0
let green = 0
let blue = 0

const interval = () => {
	return Math.floor(Math.random() * (255 - 1) + 1)
}

const setRgb = () => {
	red = interval()
	green = interval()
	blue = interval()
}

const test  = () => {
	setRgb()
	document.documentElement.style.setProperty('--red', red)
	document.documentElement.style.setProperty('--green', green) 
	document.documentElement.style.setProperty('--blue', blue)
}

button.onclick = test
```
will work exactly as intended. I even took a peek at the compiled CSS, and it compiles to completely valid css.  [Here is a codepen of this example in action](https://codepen.io/anon/pen/NMZZwx)

**Comment by thomasklein** [comment]
Hi! Thanks for all the great work on stylus, I love it!

Since `rgb` and `rgba`, `hsla `... are native color notations since [level 4](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb()) and supported in all modern browsers , they should not be proxied by stylus anymore. The described error is rather unexpected and prevents people writing modern CSS with stylus.

**Comment by Suruat** [comment]
Have same issue. Is there some plans to fix it?

**Comment by mlabod** [comment]
i think a workaround could be done like this for now!
what do you think?

```stylus
:root
  --color: #556656

opacity(variable, opacity = 1)
  // return rgba as a string so it doesn't get interpolated by stylus compiler
  s("rgba(var(%s), %s)", variable, opacity) sylus

body 
  color var(--color)
  background opacity(--color, 0.2) 
```

**Comment by phil294** [comment]
As this issue got closed, I opened another one as a feature request allowing for native `rgba` usage: #2489
