### ISSUE TITLE
Resurrection

### ISSUE THREAD

**Issue by ghost** [stylus/stylus#2414]
@tj @Panya @kizu @corysimmons @geddski @leny @yangsu @blakeembrey @akkumar @tjbenton @kaime @svallory @tonistiigi
Resurrection is exaggerated. But. Let's not leave this beautiful language to die. I know there are similar issues but we are all crying.
I am fan of intuitive, simple and fast tools. Simple tools are created by smart men. I had to use many tools like any web-dev (sass, grunt, gulp, webpack, poi, parcel etc.). Not the same category but i can easily choose Stylus as the best tool. 
If it is the time there are people who want to help including myself. 
If it is the money create a patreon account i am sure that can be fixed. 

Please, please, please. 

Edit: After fiddling around source code, i think this project needs a rewrite.

**Comment by vendethiel** [comment]
You just pinged 10 people and wrote in 15 issues. that’s not a resurrection.

**Comment by Atulin** [comment]
First SemanticUI stopped being maintained, now, while looking for whether or not I can maybe use `prodig` without `@css` in some new version, I find out there is no new version, and most probably won't be.

Just my luck I guess 🤣

**Comment by svallory** [comment]
I'm sorry guys, but I won't be able to help :/

**Comment by atilkan** [comment]
Ok, can you just point me a good book about writing language.
A man's got to do what a man's got to do.

**Comment by corysimmons** [comment]
@atilkan Regex creates ASTs.

So

```
a1:
  b1:
    add(1, 2)
  b2:
    subtract(5, 3)
```

You can use regex to see `b1` is deeper than `a1`. So you could then translate that to an abstract syntax tree (AST) that looks like this:

```js
{
  value: 'a1',
  type: 'key',
  children: [
    {
      value: 'b1',
      type: 'key',
      children: [
        {
          value: 'add(1, 2)',
          type: 'function' // determined by other regex which detects the `(...)` part
        },
        {
          // ...
        }
      ]
    }
  ]
}
```

Once you have an AST, you can do all kinds of stuff depending on if things are nested within each other and such.

Stylus uses indentation syntax so you'd need to detect keywords and indentation groups (groups of X # of spaces) to create your AST.

PostCSS (NodeJS AST for CSS) has a CSS indentation flavor you might be interested in: https://github.com/postcss/sugarss

Other stuff:

- https://astexplorer.net
- https://github.com/stylus/stylus/tree/dev/lib

**Comment by vendethiel** [comment]
Not sure if one should say "regexes create ASTs" ;-). It definitely isn't how it happens in the code.

-----------------------

First, the Lexer lexes the code. It categorizes, bit by bit, each part of the code.
`(a[b])` becomes `PAREN IDENT OP IDENT OP PAREN` (they're not uppercased in the code, it's just to mean "this is an array of tokens"). Each token type is a method, which returns itself if it parsed, or null otherwise. To dispatch, the code does `paren() || ident() || op() || ...`, since JS' `||` returns the first truthy operand.

Once that's done, the Parser will reuse these tokens to form the aforementioned AST. It uses operators like `expect` and `peek` to get the tokens and build the nodes.

The AST, being a Tree, has a starting point: the first node. The Evaluator's job is to evaluate that AST. It uses the visitor pattern (that's why it's in the "visitor" directory) to recursively "run" the stylus code.

**Comment by atilkan** [comment]
@corysimmons Thanks. 
I actually know that much about AST. I did small project before about creating language. But you gave me the idea that is enough to go. 
Also digged the source code while trying to help issues. Still alien though. Too much code for a human.
I wonder; Is SugarCSS the reason stylus doesn't get update? Because they are similar.

**Comment by atilkan** [comment]
@vendethiel Really helpful comments, thanks.

**Comment by vendethiel** [comment]
No. The regexes are used to tokenize the code first. The parser creates the AST from tokens. Those are two different steps.

**Comment by atilkan** [comment]
> No. The regexes are used to tokenize the code first. The parser creates the AST from tokens. Those are two different steps.

Ohh, i see.

**Comment by corysimmons** [comment]
Dunno/care how languages work tbh. This is more of a talk for Slack or something tho. Stylus lib code just looked like parsing to AST then doing stuff (which is what PostCSS does) so threw it out there.

Unsubbed

**Comment by sheriffderek** [comment]
If anyone wants to talk about this on a CSS Discord Server: https://discord.gg/pFc6XmH - I started one recently.

**Comment by iChenLei** [comment]
closed via https://github.com/stylus/stylus/issues/2282
