### ISSUE TITLE
Put the project up for adoption on CodeShelter

### ISSUE THREAD

**Issue by Atulin** [stylus/stylus#2433]
[https://www.codeshelter.co/](https://www.codeshelter.co/)

The project is not being maintained, might as well try to find other, active maintainers.

**Comment by sheriffderek** [comment]
With things like https://stylelint.io ignoring Stylus / and the latest commits being May 2018 - it's getting really hard to sell my teams on using Stylus. I really hope we can keep it going - but I'm not versed enough in the Node side of things to contribute yet. I can't go back to writing @include on every other line! : /  How can we help? I've been trying to show it off: https://www.codementor.io/sheriffderek/learn-stylus-right-now-b92tj26yo

**Comment by atilkan** [comment]
You can start by contributing.

**Comment by sheriffderek** [comment]
@Atulin - I think there are many ways to contribute. The code doesn't seem to need much help - compared to actual adoption. I mentioned that I'm not great with Node / and even if I spent a few years learning everything there is to know about Node and Stylus - in this case - I doubt it would change anything. I personally think it's perfect as it is. So - any meaningful contributions would likely need to be on the stylelint end of things. Thanks for the suggestion though. ; )

**Comment by atilkan** [comment]
I hear you. I also don't know about node much but javascript. Nobody wants to contribute so i am crawling inside source code for a while now.

**Comment by atilkan** [comment]
@sheriffderek 
I hear you. I also don't know about node much but javascript. Nobody wants to contribute so i am crawling inside source code for a while now. And i can tell it needs some work. 
I tried to tell this to maintainers about it. Look their response. https://github.com/stylus/stylus/issues/2414
Also DMed them. After i understood nobody wants to work on them i tried to ask some features from sass maintainers. I am blocked on sass repo because they don't event think simple file globing feature is necessary. Also i don't like sass. I probably made it obvious.
So nobody wants to work and i am not capable yet. Trying to understand the mechanism by helping issues and crawling source code in my free time.
You are welcome if you join.

**Comment by sheriffderek** [comment]
Oopps! ha. I did mean to tag you. Yeah. I'll try and help out soon!

**Comment by iChenLei** [comment]
closed
